#!/bin/bash

### BEGIN INIT INFO
# Provides:		bt-start
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	CompuLab cservice-start
### END INIT INFO

# Get the soc and revision

cservice_stop() {
	;
}

cservice_status() {
	;
}

cservice_start() {
	;
}

case "$1" in
start)
	cservice_start
	;;
stop)
	cservice_stop
	;;
status)
	cservice_status
	;;
*)
cat << eom
	Usage: $0 {start|stop|status}
eom
	exit 1
esac

exit 0
